import * as mdiIcons from '@mdi/js';

const mdi = mdiIcons as Record<string, string>;

/**
 * Mapeamento de nomes de ícones CSS para paths do @mdi/js
 * Organizados por categoria para facilitar manutenção
 */
const baseIconMap: Record<string, string> = {
  // Ícones essenciais do menu
  'home-outline': mdiIcons.mdiHomeOutline,
  'home': mdiIcons.mdiHome,
  'medical-bag': mdiIcons.mdiMedicalBag,
  'account': mdiIcons.mdiAccount,
  'account-circle': mdiIcons.mdiAccountCircle,
  'cog': mdiIcons.mdiCog,
  'cog-outline': mdiIcons.mdiCogOutline,
  'menu': mdiIcons.mdiMenu,
  'bell': mdiIcons.mdiBell,
  'bell-outline': mdiIcons.mdiBellOutline,
  'magnify': mdiIcons.mdiMagnify,
  'check': mdiIcons.mdiCheck,
  'check-circle': mdiIcons.mdiCheckCircle,
  'close': mdiIcons.mdiClose,
  'close-circle': mdiIcons.mdiCloseCircle,
  'close-circle-outline': mdiIcons.mdiCloseCircleOutline,
  'plus': mdiIcons.mdiPlus,
  'minus': mdiIcons.mdiMinus,
  'edit': mdiIcons.mdiPencil,
  'delete': mdiIcons.mdiDelete,
  'eye': mdiIcons.mdiEye,
  'eye-off': mdiIcons.mdiEyeOff,
  'star': mdiIcons.mdiStar,
  'star-outline': mdiIcons.mdiStarOutline,
  'upload': mdiIcons.mdiUpload,
  'cloud-upload': mdiIcons.mdiCloudUpload,
  'download': mdiIcons.mdiDownload,
  'refresh': mdiIcons.mdiRefresh,
  'search': mdiIcons.mdiMagnify,
  'settings': mdiIcons.mdiCog,
  'calendar': mdiIcons.mdiCalendar,
  'calendar-blank': mdiIcons.mdiCalendarBlank,
  'calendar-check': mdiIcons.mdiCalendarCheck,
  'briefcase': mdiIcons.mdiBriefcase,
  'layers': mdiIcons.mdiLayers,
  'text-box': mdiIcons.mdiTextBox,
  'gesture-tap': mdiIcons.mdiGestureTap,
  'clock': mdiIcons.mdiClock,
  'clock-outline': mdiIcons.mdiClockOutline,
  'format-list-bulleted': mdiIcons.mdiFormatListBulleted,
  'application': mdiIcons.mdiApplication,
  'play-circle': mdiIcons.mdiPlayCircle,
  'pause': mdiIcons.mdiPause,
  'stop': mdiIcons.mdiStop,
  'fullscreen': mdiIcons.mdiFullscreen,
  'fullscreen-exit': mdiIcons.mdiFullscreenExit,
  'code-tags': mdiIcons.mdiCodeTags,
  'heart': mdiIcons.mdiHeart,
  'information': mdiIcons.mdiInformation,
  'alert': mdiIcons.mdiAlert,
  'alert-circle': mdiIcons.mdiAlertCircle,
  'cancel': mdiIcons.mdiCancel,
  'chevron-down': mdiIcons.mdiChevronDown,
  'chevron-left': mdiIcons.mdiChevronLeft,
  'chevron-right': mdiIcons.mdiChevronRight,
  'chevron-up': mdiIcons.mdiChevronUp,
  'clipboard-list': mdiIcons.mdiClipboardList,
  'chart-areaspline': mdiIcons.mdiChartLine,
  'numeric-0': mdiIcons.mdiNumeric0,
  'numeric-9-plus': mdiIcons.mdiNumeric9Plus,
  'circle-slice-8': mdiIcons.mdiCircleSlice8,
  'card-text': mdiIcons.mdiCardText,
  'page-layout-header': mdiIcons.mdiPageLayoutHeader,
  'page-layout-footer': mdiIcons.mdiPageLayoutFooter,
  'star-circle': mdiIcons.mdiStarCircle,
  'label': mdiIcons.mdiLabel,
  'cursor-pointer': mdiIcons.mdiCursorPointer,
  'email': mdiIcons.mdiEmail,
  'message': mdiIcons.mdiMessage,
  'cart': mdiIcons.mdiCart,
  'clipboard-check': mdiIcons.mdiClipboardCheck,
  'cookie': mdiIcons.mdiCookie,
  'lightning-bolt': mdiIcons.mdiLightningBolt,
  'reload': mdiIcons.mdiReload,
  'tune': mdiIcons.mdiTune,
  'shape': mdiIcons.mdiShape,
  'palette': mdiIcons.mdiPalette,
  'palette-swatch': mdiIcons.mdiPaletteSwatch,
  'gradient-horizontal': mdiIcons.mdiGradientHorizontal,
  'resize': mdiIcons.mdiResize,
  'border-radius': mdiIcons.mdiBorderRadius,
  'numeric': mdiIcons.mdiNumeric,
  'arrow-all': mdiIcons.mdiArrowAll,
  'arrow-right': mdi.mdiArrowRight,
  'badge-outline': mdi.mdiBadgeAccountOutline,
  'open-in-new': mdiIcons.mdiOpenInNew,
  'logout': mdiIcons.mdiLogout,
  'view-carousel': mdiIcons.mdiViewCarousel,
  'waves': mdiIcons.mdiWaves,
  'card-bulleted': mdiIcons.mdiCardBulleted,
  'chart-line': mdiIcons.mdiChartLine,
  'currency-eur': mdiIcons.mdiCurrencyEur,
  'currency-usd': mdiIcons.mdiCurrencyUsd,
  'package-variant': mdiIcons.mdiPackageVariant,
  'laptop': mdiIcons.mdiLaptop,
  'heart-outline': mdiIcons.mdiHeartOutline,
  'help': mdiIcons.mdiHelp,
  'view-grid': mdiIcons.mdiViewGrid,
  'format-title': mdiIcons.mdiFormatTitle,
  'account-group': mdiIcons.mdiAccountGroup,
  'account-star': mdiIcons.mdiAccountStar,
  'account-plus': mdiIcons.mdiAccountPlus,
  'cash': mdiIcons.mdiCash,
  'account-edit': mdiIcons.mdiAccountEdit,
  'account-heart': mdiIcons.mdiAccountHeart,
  'lifebuoy': mdiIcons.mdiLifebuoy,
  'puzzle': mdiIcons.mdiPuzzle,
  'state-machine': mdiIcons.mdiStateMachine,
  'bug': mdiIcons.mdiBug,
  'chevron-double-left': mdiIcons.mdiChevronDoubleLeft,
  'chevron-double-right': mdiIcons.mdiChevronDoubleRight,
  'stethoscope': mdiIcons.mdiStethoscope,
  'pill': mdiIcons.mdiPill,
  'account-multiple': mdiIcons.mdiAccountMultiple,
  'content-save': mdiIcons.mdiContentSave,
  'dots-vertical': mdiIcons.mdiDotsVertical,
  'earth': mdiIcons.mdiEarth,
  'file': mdiIcons.mdiFile,
  'file-chart': mdiIcons.mdiFileChart,
  'filter': mdiIcons.mdiFilter,
  'folder': mdiIcons.mdiFolder,
  'folder-open': mdiIcons.mdiFolderOpen,
  'image': mdiIcons.mdiImage,
  'image-check': mdiIcons.mdiImageCheck,
  'image-broken': mdiIcons.mdiImageBroken,
  'file-image-plus': mdiIcons.mdiFileImagePlus,
  'swap-horizontal': mdiIcons.mdiSwapHorizontal,
  'link': mdiIcons.mdiLink,
  'lock': mdiIcons.mdiLock,
  'lock-open': mdiIcons.mdiLockOpen,
  'map': mdiIcons.mdiMap,
  'map-marker': mdiIcons.mdiMapMarker,
  'phone': mdiIcons.mdiPhone,
  'send': mdiIcons.mdiSend,
  'share': mdiIcons.mdiShare,
  'sync': mdiIcons.mdiSync,
  'tab': mdiIcons.mdiTab,
  'table': mdiIcons.mdiTable,
  'table-cog': mdiIcons.mdiTableCog,
  'table-remove': mdiIcons.mdiTableRemove,
  'tag': mdiIcons.mdiTag,
  'thumb-up': mdiIcons.mdiThumbUp,
  'trash-can': mdiIcons.mdiTrashCan,
  'video': mdiIcons.mdiVideo,
  'volume-high': mdiIcons.mdiVolumeHigh,
  'volume-off': mdiIcons.mdiVolumeOff,
  'wifi': mdiIcons.mdiWifi,
  'wifi-off': mdiIcons.mdiWifiOff,
  'moon-waning-crescent': mdiIcons.mdiMoonWaningCrescent,
  'white-balance-sunny': mdiIcons.mdiWhiteBalanceSunny,
  'crown': mdiIcons.mdiCrown,
  'crown-outline': mdiIcons.mdiCrownOutline,
  'cloud-check': mdiIcons.mdiCloudCheck,
  'cloud-off-outline': mdiIcons.mdiCloudOffOutline,
  'window-close': mdiIcons.mdiWindowClose,
  'window-maximize': mdiIcons.mdiWindowMaximize,
  'window-minimize': mdiIcons.mdiWindowMinimize,
  'window-restore': mdiIcons.mdiWindowRestore,
  'zoom-in': mdiIcons.mdiMagnifyPlus,
  'zoom-out': mdiIcons.mdiMagnifyMinus,

  // Ícones adicionais que estavam faltando
  'tooltip-text': mdiIcons.mdiTooltipText,
  'dock-left': mdiIcons.mdiDockLeft,
  'dock-top': mdiIcons.mdiDockTop,
  'dock-right': mdiIcons.mdiDockRight,
  'dock-bottom': mdiIcons.mdiDockBottom,
  'view-dashboard': mdiIcons.mdiViewDashboard,
  'calendar-clock': mdiIcons.mdiCalendarClock,
  'calendar-range': mdiIcons.mdiCalendarRange,
  'gamepad-variant': mdiIcons.mdiGamepadVariant,

  // Mais ícones faltando do GSSelectShowcase
  'asterisk': mdiIcons.mdiAsterisk,
  'block-helper': mdiIcons.mdiBlockHelper,
  'eye-check': mdiIcons.mdiEyeCheck,
  'arrow-right-box': mdiIcons.mdiArrowRightBox,
  'arrow-expand-horizontal': mdiIcons.mdiArrowExpandHorizontal,
  'checkbox-marked': mdiIcons.mdiCheckboxMarked,
  'checkbox-multiple-marked': mdiIcons.mdiCheckboxMultipleMarked,
  'cloud-download': mdiIcons.mdiCloudDownload,
  'check-decagram': mdiIcons.mdiCheckDecagram,
  'form-select': mdiIcons.mdiFormSelect,
  'loading': mdiIcons.mdiLoading,
  'alert-outline': mdiIcons.mdiAlertOutline,
  'checkbox-blank-outline': mdiIcons.mdiCheckboxBlankOutline,
  'group': mdiIcons.mdiGroup,
  'target': mdiIcons.mdiTarget,
  'circle': mdiIcons.mdiCircle,
  'circle-outline': mdiIcons.mdiCircleOutline,
  'progress-clock': mdiIcons.mdiProgressClock,
  'alert-octagon': mdiIcons.mdiAlertOctagon,
  'archive-alert': mdiIcons.mdiArchiveAlert,
  'image-off': mdiIcons.mdiImageOff,
  'palette-advanced': mdiIcons.mdiPaletteAdvanced,
  'menu-down': mdiIcons.mdiMenuDown,
  'react': mdiIcons.mdiReact,
  'language-typescript': mdiIcons.mdiLanguageTypescript,
  'nodejs': mdiIcons.mdiNodejs,
  'format-list-bulleted-type': mdiIcons.mdiFormatListBulletedType,
  'wrench': mdiIcons.mdiWrench,
  'plus-circle': mdiIcons.mdiPlusCircle,
  'help-circle': mdiIcons.mdiHelpCircle,
  'lightbulb': mdiIcons.mdiLightbulb,
  'view-column': mdiIcons.mdiViewColumn,
  'filter-remove': mdiIcons.mdiFilterRemove,
  'unfold-more-horizontal': mdiIcons.mdiUnfoldMoreHorizontal,
  'file-image-plus-outline': mdiIcons.mdiFileImagePlusOutline,
  'camera': mdiIcons.mdiCamera,
  'camera-flip': mdiIcons.mdiCameraFlip,
  'camera-plus-outline': mdiIcons.mdiCameraPlusOutline,
  'rotate-right': mdiIcons.mdiRotateRight,
  'flip-horizontal': mdiIcons.mdiFlipHorizontal,
  'flip-vertical': mdiIcons.mdiFlipVertical,
  'crop': mdiIcons.mdiCrop,
  'trash-can-outline': mdiIcons.mdiTrashCanOutline,
  'weather-sunny': mdiIcons.mdiWeatherSunny,
  'weather-night': mdiIcons.mdiWeatherNight,
  'information-outline': mdiIcons.mdiInformationOutline,
  'alert-circle-outline': mdiIcons.mdiAlertCircleOutline,
  'arrow-left': mdiIcons.mdiArrowLeft,
  'arrow-up': mdiIcons.mdiArrowUp,
  'login': mdiIcons.mdiLogin,
  'new-box': mdiIcons.mdiNewBox,
  'pencil': mdiIcons.mdiPencil,
  'share-variant': mdiIcons.mdiShareVariant,
  'calendar-month': mdiIcons.mdiCalendarMonth,
  'calendar-week': mdiIcons.mdiCalendarWeek,
  'clock-end': mdiIcons.mdiClockEnd,
  'calendar-import': mdiIcons.mdiCalendarImport,
  'calendar-export': mdiIcons.mdiCalendarExport,
  'calendar-today': mdiIcons.mdiCalendarToday,
  'clock-check': mdiIcons.mdiClockCheck,
  'history': mdiIcons.mdiHistory,
  'link-variant': mdiIcons.mdiLinkVariant,
};

const extraIcons: Record<string, string> = {
  // Ícones faltando do menu
  'file-document-outline': mdiIcons.mdiFileDocumentOutline,
  'file-document': mdiIcons.mdiFileDocument,
  'file-document-multiple-outline': mdiIcons.mdiFileDocumentMultipleOutline,
  'file-document-multiple': mdiIcons.mdiFileDocumentMultiple,
  'tools': mdiIcons.mdiTools,
  'cellphone': mdiIcons.mdiCellphone,
  'account-switch': mdiIcons.mdiAccountSwitch,
  'calendar-plus': mdiIcons.mdiCalendarPlus,
  'certificate': mdiIcons.mdiCertificate,
  'heart-pulse': mdiIcons.mdiHeartPulse,
  'human': mdiIcons.mdiHuman,
  'tooth': mdiIcons.mdiTooth,
  'pill-multiple': mdiIcons.mdiPillMultiple,
  'doctor': mdiIcons.mdiDoctor,
  'domain': mdiIcons.mdiDomain,
  'hospital': mdiIcons.mdiHospital,
  'truck': mdiIcons.mdiTruck,
  'office-building': mdiIcons.mdiOfficeBuilding,
  'account-hard-hat': mdiIcons.mdiAccountHardHat,
  'content-copy': mdiIcons.mdiContentCopy,
  'update': mdiIcons.mdiUpdate,
  'merge': mdiIcons.mdiMerge,
  'book': mdiIcons.mdiBook,
  'book-open': mdiIcons.mdiBookOpen,
  'file-export': mdiIcons.mdiFileExport,
  'test-tube': mdiIcons.mdiTestTube,
  'bank': mdiIcons.mdiBank,
  'card-account-details': mdiIcons.mdiCardAccountDetails,
  'shield': mdiIcons.mdiShield,
  'shield-account': mdiIcons.mdiShieldAccount,
  'drag': mdiIcons.mdiDrag,
  'drag-horizontal': mdiIcons.mdiDragHorizontal,
  'drag-vertical': mdiIcons.mdiDragVertical,
  'form-textbox': mdiIcons.mdiFormTextbox,
  'form-textarea': mdiIcons.mdiFormTextarea,
  'radiobox-marked': mdiIcons.mdiRadioboxMarked,
  'toggle-switch': mdiIcons.mdiToggleSwitch,
  'gesture-tap-button': mdiIcons.mdiGestureTapButton,
  'format-text': mdiIcons.mdiFormatText,
  'compass-outline': mdiIcons.mdiCompassOutline,
  'view-list': mdiIcons.mdiViewList,
  'view-grid-plus': mdiIcons.mdiViewGridPlus,
  'file-outline': mdiIcons.mdiFileOutline,
  'progress-download': mdiIcons.mdiProgressDownload,
  'card-text-outline': mdiIcons.mdiCardTextOutline,
  'table-large': mdiIcons.mdiTableLarge,
  'bell-ring': mdiIcons.mdiBellRing,
  // Contadores e tipografia (GSTextArea, etc.)
  'text': mdiIcons.mdiText,
  'format-letter-case': mdiIcons.mdiFormatLetterCase,
  'format-line-spacing': mdiIcons.mdiFormatLineSpacing,
};

const iconCache = new Map<string, string>();

export async function resolveMdiPath(name: string, debug?: boolean): Promise<string | null> {
  const cleanName = name.replace(/^mdi\s+/, '').replace(/^mdi-/, '');
  if (iconCache.has(cleanName)) {
    return iconCache.get(cleanName)!;
  }

  if (iconMap[cleanName]) {
    iconCache.set(cleanName, iconMap[cleanName]);
    return iconMap[cleanName];
  }

  const exportName = `mdi${cleanName.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/^([a-z])/, (_, c) => c.toUpperCase())}`;

  try {
    const iconsModule = (await import('@mdi/js')) as unknown as Record<string, string>;
    const path = iconsModule[exportName];
    if (path) {
      iconCache.set(cleanName, path);
      return path;
    }
  } catch (error) {
    if (debug) {
      console.warn(`[GSIcon] Falha ao importar ícone ${exportName}:`, error);
    }
  }

  return null;
}

export const iconMap: Record<string, string> = {
  ...baseIconMap,
  ...extraIcons,
};
